# Generated by Django 5.2.5 on 2025-08-22 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=9)),
                ('term', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.class')),
            ],
            options={
                'unique_together': {('class_level', 'academic_year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=15)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('paystack', 'Paystack'), ('cash', 'Cash'), ('bank_deposit', 'Bank Deposit')], default='paystack', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('paystack_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('paystack_authorization', models.JSONField(blank=True, null=True)),
                ('paystack_transfer_code', models.CharField(blank=True, max_length=100)),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice')),
            ],
        ),
    ]
