# Generated by Django 5.2.5 on 2025-08-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_payment_original_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
