# Generated by Django 5.2.5 on 2025-08-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_reportcard_is_finalized_reportcard_pdf_file'),
        ('finance', '0003_feestructure_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='class_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.class'),
        ),
    ]
