# Generated by Django 5.2.5 on 2025-08-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcard',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='report_cards/'),
        ),
    ]
